---
 - name: Implementation of apache webserver
   hosts: rhel
   serial: 1
   tasks:
    
    - name: install apache software
      dnf:
        name: httpd
        state: latest

    - name: start and enable service
      service:
        name: httpd
        enabled: yes
