---
 - name: Implement NFS Server
   hosts: '{{nfs_server}}'
   vars_files: ../vars/nfs.yml
   tasks:
    
    - name: install nfs software
      yum:
        name: nfs-utils
        state: latest

    - name: start and enable service
      service:
        name: nfs-server
        state: started
        enabled: yes

    - name: create a share directory
      file:
        path: '{{share_dir}}'
        state: directory

    - name: edit configuration
      lineinfile:
        path: /etc/exports
        line: '{{share_dir}}  {{nfs_client}}{{perm}}'
        state: present

    - name: update
      shell:
        cmd: exportfs -r

 - name: Implement NFS Client
   hosts: '{{nfs_client}}'
   vars_files: ../vars/nfs.yml
   tasks:


    - name: install pkg
      yum:
        name: nfs-utils
        state: present
    
    - name: Mount NFS Share
      mount:
        path: '{{mount_point}}'
        src: '{{nfs_server}}:{{share_dir}}'
        fstype: nfs
        state: mounted
