---
 - name: create two users and install two softwares
   hosts: all
   vars_files: ../vars/loop_vars.yml
   tasks:
    
    - name: ensure users are '{{st}}'
      user:
        name: '{{item}}'
        state: '{{st}}'
      loop: '{{users}}'

    - name: ensure softwares is '{{st}}'
      yum:
        name: '{{item}}'
        state: '{{st}}'
      with_items: '{{softwares}}'
      when: ansible_facts['os_family'] == "RedHat"

    - name: install 4 ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"


